### ISSUE TITLE
麻烦完善一下使用文档

### ISSUE THREAD

**Issue by gaoyong06** [JiangJuHong/FlutterTextSpanField#1]
感谢作者，做了一个很有用的插件
特别建议，把使用文档完善完善，因为这样能提高很大的沟通效率

**Comment by gaoyong06** [comment]
例如我这些现在需求是，@用户  的格式是 @[Mention:987734,王老师]
(前面的987734 是用户的uid)

实际上输入框里面的内容是：

@[Mention:987734,王老师] 早上好

但是用户看输入框的时候里面是

**@王老师** 早上好

这样，所以涉及到一个文字模式， 和显示样式 替换的工作
这个 使用 FlutterTextSpanField 应该如何实现呢？

**Comment by JiangJuHong** [comment]
你好，这个插件只是对文本域的样式就行封装，没有涉及到隐藏域值，你可以参考微信的设计对用户名进行匹配。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaoyong <notifications@github.com&gt;
发送时间: 2020年4月14日 20:20
收件人: JiangJuHong/FlutterTextSpanField <FlutterTextSpanField@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTextSpanField] 麻烦完善一下使用文档 (#1)






例如我这些现在需求是，@用户  的格式是 @[Mention:987734,王老师]
(前面的987734 是用户的uid)

实际上输入框里面的内容是：

@[Mention:987734,王老师] 早上好

但是用户看输入框的时候里面是

@王老师 早上好

这样，所以设计到一个文字模式， 和显示样式 替换的工作
这个 使用 FlutterTextSpanField 应该如何实现呢？
