### ISSUE TITLE
cursorColor != null

### ISSUE THREAD

**Issue by JamalJo** [JiangJuHong/FlutterTextSpanField#17]
➜  mac flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G2005 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.59.1)
[✓] Connected device (3 available)

• No issues found!

**Comment by JiangJuHong** [comment]
请提供详细的错误代码以及付现步骤。
