### ISSUE TITLE
微信表情

### ISSUE THREAD

**Issue by yuanbin-dev** [JiangJuHong/FlutterTextSpanField#3]
输入[微笑]会显示微笑图片会计划搞不

**Comment by JiangJuHong** [comment]
你好，该插件不是“输入框多组件渲染”，而是“输入框多样式渲染”，所谓的多样式，指的是文本样式，也就是 TextStyle对象，与你的需求不符. 如果你需要在输入框中显示其它组件，请参考其它插件. 该问题将会被关闭. 感谢你的支持.
