### ISSUE TITLE
系统删除键如何整体删除

### ISSUE THREAD

**Issue by cherrybiu** [JiangJuHong/FlutterTextSpanField#5]
hi, 感谢大佬实现的这个组件.
但我在使用的过程中有点问题,就是那个删除整体那一块,除了使用删除按钮来定义回调,对textField自带的删除键删除是无效的是吗

**Comment by JiangJuHong** [comment]
自带的删除键有效呀，你使用的是什么平台呢？

**Comment by JiangJuHong** [comment]
目前IOS平台有一点故障，Android不影响正常使用。我会在近期忙空后对这个BUG修复。

**Comment by cherrybiu** [comment]
> 忙

对,就是在ios上面,删除有异常. 好的, 期待大佬的更新

**Comment by JiangJuHong** [comment]
release: v2.0.5
